### PR TITLE
Fixes wordplate/extended-acf#82

### LINKED ISSUE #82: Cannot disable the Taxonomy field's add_term option
I can see that this library's `Taxonomy::createTerm` method is a wrapper for ACF's `add_term`.
Since this is an additive option, I was expecting new term creation to be disabled while editing if createTerm wasn't used.
Looking at the [official ACF docs for registering fields via php](https://www.advancedcustomfields.com/resources/register-fields-via-php/#relational), it appears that `add_term` is true by default.

## Expected Behavior

Should **Allow** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy')
  ->createTerms();
```

Should **Not allow** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy');
```

## Actual Behavior

**Allows** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy')
  ->createTerms();
```

**Allows** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy');
```

## Versions

  - WordPlate: 5.5.3
  - PHP: 7.4.12

Thank you and terrific job with this package! 🙌🏼

### PR DESCRIPTION
**Pull request by josephfusco**
This PR fixes #82 by adding allowing a user to pass a boolean to `Taxonomy::createTerms`.
No argument defaults to `true` for backwards compatibility.

### CODE REVIEW

File: src/Fields/Taxonomy.php [hunk 1]
```diff
@@ -44,23 +44,23 @@ public function appearance(string $fieldType): self
         return $this;
     }
 
-    public function createTerms(): self
+    public function addTerm(bool $addTerm = true): self
```
Comment (josephfusco) [inline src/Fields/Taxonomy.php:47]: Using addTerm (singular) to match ACF https://github.com/AdvancedCustomFields/acf/blob/37fcf7204f034c0dcdf8240ffa6d802a238431dc/includes/fields/class-acf-field-taxonomy.php#L788

**Comment by vinkla** [comment]
Thanks for working on this Jospeh! You may use this with the new branch alias 9.0.
